[SMTP] Отправка писем используя свой smtp наследованный от Джаго
garpixcms/garpix_notify pull request #1
Opened 2021-06-29 15:48 UTC by MarychevGarpix

2021-06-30 05:49 UTC, crusat requested changes

2021-06-30 05:49 UTC, crusat commented on backend/garpix_notify/smtp.py
> +    smtp = SMTPAccount.get_free_smtp()
Таким образом, только единожды будет получен smtp аккаунт, а не каждый раз. Идея в том, чтобы была ротация нескольких SMTP аккаунтов.

2021-06-30 05:49 UTC, crusat commented on backend/garpix_notify/models/notify.py
> +            self.send_email_by_django()
Лучше заменить стандартный старый send_email, на новый, а не добавлять еще одну функцию. Все равно старая уже не используется.

2021-06-30 05:49 UTC, crusat commented on backend/app/__init__.py
> +__all__ = ('celery_app',)
Не очень понимаю, зачем это?

2021-06-30 05:49 UTC, crusat commented on backend/garpix_notify/smtp.py
> +    raise ("[SMTPAccount not found] Проверьте настроки в админке : /admin/garpix_notify/smtpaccount/", e)
Если почта будет выключена или не будет ни одного SMTP-аккаунта, то смс и пуши тоже отправляться не будут. Т.к. не запустится селери.

2021-06-30 05:49 UTC, crusat commented on backend/garpix_notify/models/notify.py
> +    def _get_valid_smtp_account(self) -> Optional[SMTPAccount]:
Функция проверяет больше, чем называется - не только смтп аккаунт ищет, но и проверяет пользователя на активность. Вообще, так делать нельзя - т.к. через notify отправляются письма неактивированным пользователям (подтвердите емейл, например). Также, стоит оставить эту функцию в смтп аккаунтах, т.к. ей там место и они лучше знают заняты они или свободны.

2021-06-30 14:19 UTC, MarychevGarpix commented on backend/garpix_notify/smtp.py
> +    smtp = SMTPAccount.get_free_smtp()
Это первоначальная инициализация настроек для отправки Email. 
Дальше они будут изменяться при обращении к функции Notify.send(...)
Если SMTPAccount настроки не будут установлены админом по ошибке будет понятно что нужно создать SMTPAccount(ы).
В NotifyConfig(SingleModel) по умолчанию настрока включена. Это гаратирует что письма по дефолту будут отправляться.
Если не хотим - снимаем галку и Уведомление создастся со статусом "Отклонено" (как и задумывалось).

Когда пользователь захочет отправлять сообщения система проверяет `[V] Разрешить отправку Email` в NotifyConfig.
При каждой новой отправке письма проверяется свежий аккаунт SMTPAccount.get_free_smtp().
Ниже пример как это происходит (этот код не менялся)
```
    config = NotifyConfig.get_solo()
    if not config.is_email_enabled:
        self.state = STATE.DISABLED
        return

    account = SMTPAccount.get_free_smtp()
    self.sender_email = account.sender
    if account is None or not account.is_active:
        return

    return account
```
Таким образом, постоянно будет проверятся актуальный smtp аккаунт!

2021-06-30 14:22 UTC, MarychevGarpix commented on backend/garpix_notify/smtp.py
> +    raise ("[SMTPAccount not found] Проверьте настроки в админке : /admin/garpix_notify/smtpaccount/", e)
Если почта будет выключена то на смс и пуши это никак не повлияет. 
Селери мы вроде как запускаем сами а не кодом. (если я правильно понял текущую реализацию)
Также есть упоминание об этом в документации
__Do not forget run celery:__
```
celery -A app worker --loglevel=info -B
```

2021-06-30 16:04 UTC, MarychevGarpix commented on backend/app/__init__.py
> +__all__ = ('celery_app',)
Такие рекомендации дает [Celery документация](https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html):
```
# Это гарантирует, что приложение всегда импортируется, 
# когда Django запускается, поэтому shared_task будет использовать это приложение.
from .celery import app as celery_app
__all__ = ('celery_app',)
```

2021-07-01 12:57 UTC, MarychevGarpix commented on backend/garpix_notify/models/notify.py
> +    def _get_valid_smtp_account(self) -> Optional[SMTPAccount]:
Я решил избавиться пока от создания доп. функций, и вернул старую реализацию. Т.к. она более читабельнее и используется в 1м месте

2021-07-01 12:58 UTC, MarychevGarpix commented on backend/garpix_notify/models/notify.py
> +            self.send_email_by_django()
Done

2021-07-02 07:39 UTC, merged